mlogparser:	mlogparser.c
	gcc -O2 -g mlogparser.c -o mlogparser

#Case imagining two more files test_common.c and rpi_pmu, each with a header
#mlogparser:	mlogparser.c test_common.h \
#	test_common.c \
#	rpi_pmu.h  rpi_pmu.c
#	gcc -c rpi_pmu.c 
#	gcc -c test_common.c
#	gcc -O2 -c mlogparser.c
#	gcc -o mlogparser mlogparser.o test_common.o rpi_pmu.o
 
clean:
	rm mlogparser
#	rm mlogparser *.o
